---
description: "Royal Hackaway hosts hackathons organised by students for students at Royal Holloway, University of London."
author: "Benzi <hi@benzi.io>"
include: ["index.html", "_pages"]

display_ad: false
maintenance: false

navs:
  -
    name: Home
    path: top
  -
    name: About
    path: about
  -
    name: Sponsors
    path: sponsors
  -
    name: Schedule
    path: schedule
  -
    name: FAQ
    path: faq
socials:
  -
    icon: icon-s-facebook
    name: Facebook
    url: "https://facebook.com/royalhackaway"
  -
    icon: icon-s-twitter
    name: Twitter
    url: "https://twitter.com/royalhackaway"

email: hello@royalhackaway.com
event:
  public: true
  date: "2018-01-13T10:00:00+00:00"
  name: "Royal Hackaway 2019"
  details: "Royal Hackaway 2019 is a 24 hour hackathon taking place on the 2nd-3rd January 2018. This is great opportunity for creative inventors, designers and programmers to come together to create awesome projects."
  location: "Windsor Building, Royal Holloway, UoL"
  map:
    coords:
      lat: "51.4253791"
      lng: "-0.5674995"
    placeID: "ChIJXUCjP_55dkgR4OIhA2pQA6A"
  venue_floor_plan: ""
  tickets: "https://tickets.royalhackaway.com/"
  start: "2019-02-02T12:00:00+00:00"
  end: "2019-02-03T12:00:00+00:00"
  internet:
    ssid: "CampusNet"
    username: "Hackathon"
    password: "LjMTQEj5"

sponsors:
  gold: []
  silver: []
  bronze: []
  partner:
    -
      color: "#0F0D0E"
      description: "GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside millions of other developers."
      logo: /assets/images/github.svg
      name: GitHub
      shade: dark
      url: "https://github.com"
    -
      color: "#FFF"
      description: "Major League Hacking (MLH) is the official student hackathon league."
      logo: /assets/images/mlh.svg
      name: MLH
      shade: light
      url: "https://mlh.io"
    -
      color: "#FFF"
      description: "Majestic: The planet's largest Link Index database"
      logo: /assets/images/majestic.png
      name: Majestic
      shade: light
      url: "https://majestic.com"
    -
      color: "#FFF"
      description: "Department of Computer Science at Royal Holloway, University of London"
      logo: /assets/images/rhul-logo.svg
      name: "Department of Computer Science"
      shade: light
      url: "https://www.royalholloway.ac.uk/computerscience/home.aspx"


collections:
  events:
    output: true
    permalink: /:slug
