---
repository: royalhackaway/royalhackaway.github.io
include: ["index.html", "_pages"]

display_ad: true

footer-description: "Royal Hackaway is a student-run group that hosts hackathons at Royal Holloway, University of London."

navs:
  -
    name: Home
    link: "#top"
  -
    name: Events
    link: "#future-events"
  -
    name: Sponsor us
    link: "/assets/pdf/sponsordeck.pdf"
socials:
  -
    icon: "facebook-white.svg"
    name: Facebook
    url: "https://facebook.com/royalhackaway"
  -
    icon: "twitter.svg"
    name: Twitter
    url: "https://twitter.com/royalhackaway"
  -
    icon: "github-mark.png"
    name: GitHub
    url: "https://github.com/royalhackaway"

email: hello@royalhackaway.com

sponsors:
  gold: 
    -
      color: "#0F0D0E"
      text-color: "white"
      description: "GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside millions of other developers."
      logo: /assets/images/github.svg
      name: GitHub
      shade: dark
      url: "https://github.com"
  silver: 
    -
      color: "#FFF"
      text-color: "black"
      description: "Majestic: The planet's largest Link Index database"
      logo: /assets/images/majestic.png
      name: Majestic
      shade: light
      url: "https://majestic.com"
  bronze: []
  partner:
    -
      color: "#FFF"
      text-color: "black"
      description: "Major League Hacking (MLH) is the official student hackathon league."
      logo: /assets/images/mlh.svg
      name: MLH
      shade: light
      url: "https://mlh.io"
    -
      color: "#FFF"
      text-color: "black"
      description: "Department of Computer Science at Royal Holloway, University of London"
      logo: /assets/images/rhul-logo.svg
      name: "Department of Computer Science"
      shade: light
      url: "https://www.royalholloway.ac.uk/computerscience/home.aspx"


collections:
  events:
    output: true
    permalink: /:slug


sass:
  style: compressed
  sass_dir: _sass
