description: 'Royal Hackaway is a 24 hour student hackathon hosted at Royal Holloway on the 13th to the 14th of January 2018/'
author: Benzi <hi@benzi.io>
email: sponsors@royalhackaway.xyz
navs:
  - {name: Home, path: /}
  - {name: About, path: /about}
  - {name: Sponsors,path: /sponsors}
  - {name: Schedule, path: /schedule}
  - {name: Code of Conduct, path: /coc}
socials:
  - {name: Facebook, url: '#', icon: icon-s-facebook}
  - {name: Twitter, url: 'https://twitter.com/royalhackaway', icon: icon-s-twitter}
sponsors: {
  gold: [
  ], silver: [
  ], bronze: [
  ], partner: [
    {
      name: GitHub,
      description: 'GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside millions of other developers.',
      url: 'https://github.com',
      logo: '/assets/images/github.svg',
      shade: dark,
      color: '#0f0d0e'
    }, 
    {
      name: MLH,
      description: 'Major League Hacking (MLH) is the official student hackathon league.',
      url: 'https://mlh.io',
      logo: '/assets/images/mlh.svg',
      shade: light,
      color: '#ffffff'
    }
  ]
}
event: {
  public: false,
  name: Hackathon 2018,
  details: 'Royal Hackaway is a 24 hour student hackathon hosted at Royal Holloway on the 13th to the 14th of January 2018 where the most creative inventors, desginers and {{}} come together and make awesome projects!',
  schedule: {
    'Saturday' : [
      ['10:00', 'asdf'],
      ['11:00', 'asdf'],
      ['12:00', 'asdf'],
      ['13:00', 'asdf'],
      ['14:00', 'asdf'],
      ['15:00', 'asdf'],
      ['16:00', 'asdf'],
      ['17:00', 'asdf'],
      ['18:00', 'asdf'],
      ['19:00', 'asdf'],
      ['20:00', 'asdf'],
      ['21:00', 'asdf']
    ],
    'Sunday': [
      ['10:00', 'fdsa'],
      ['11:00', 'fdsa'],
      ['12:00', 'fdsa'],
      ['13:00', 'fdsa'],
      ['14:00', 'fdsa'],
      ['15:00', 'fdsa'],
      ['16:00', 'fdsa'],
      ['17:00', 'fdsa'],
      ['18:00', 'fdsa'],
      ['19:00', 'fdsa'],
      ['20:00', 'fdsa'],
      ['21:00', 'fdsa']
    ]
  },
  date: '2018-01-13T10:10:00+00:00',
  location: 'Royal Holloway, Windsor Building',
  tickets: 'https://www.eventbrite.co.uk/e/royal-hackaway-tickets-39231435279'
}
